CREATE DATABASE MARTIAL_ARTS;
USE MARTIAL_ARTS;

-- STUDENTS TABLE
CREATE TABLE STUDENTS (
    STU_ID INT NOT NULL,
    NAME VARCHAR(50),
    DOB DATE,
    JOIN_DATE DATE,
    PRIMARY KEY (STU_ID)
);

-- INSTRUCTORS TABLE 
CREATE TABLE INSTRUCTORS (
    STU_ID INT NOT NULL,
    PROMOTION_DATE DATE,
    COMPENSATION_STATUS VARCHAR(20),
    COMPENSATION_AMOUNT DECIMAL(10,2),
    PRIMARY KEY (STU_ID),
    FOREIGN KEY (STU_ID) REFERENCES STUDENTS(STU_ID)
);

-- CLASSES TABLE
CREATE TABLE CLASSES (
    CLASS_ID INT NOT NULL,
    RANK VARCHAR(20),
    DAY VARCHAR(20),
    TIME TIME,
    LOCATION VARCHAR(50),
    INSTRUCTOR_ID INT NOT NULL,
    PRIMARY KEY (CLASS_ID),
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(STU_ID)
);

-- CLASS_MEETINGS TABLE
CREATE TABLE CLASS_MEETINGS (
    MEETING_ID INT NOT NULL,
    CLASS_ID INT NOT NULL,
    MEETING_DATE DATE,
    PRIMARY KEY (MEETING_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID)
);

-- ATTENDANCE TABLE
CREATE TABLE ATTENDANCE (
    MEETING_ID INT NOT NULL,
    STU_ID INT NOT NULL,
    PRIMARY KEY (MEETING_ID, STU_ID),
    FOREIGN KEY (MEETING_ID) REFERENCES CLASS_MEETINGS(MEETING_ID),
    FOREIGN KEY (STU_ID) REFERENCES STUDENTS(STU_ID)
);

-- MEETING_ROLES TABLE
CREATE TABLE MEETING_ROLES (
    MEETING_ID INT NOT NULL,
    INSTRUCTOR_ID INT NOT NULL,
    ROLE VARCHAR(50), 
    PRIMARY KEY (MEETING_ID, INSTRUCTOR_ID),
    FOREIGN KEY (MEETING_ID) REFERENCES CLASS_MEETINGS(MEETING_ID),
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(STU_ID)
);

-- RANKS TABLE
CREATE TABLE RANKS (
    RANK_ID INT NOT NULL,
    RANK_NAME VARCHAR(30),
    BELT_COLOR VARCHAR(20),
    PRIMARY KEY (RANK_ID)
);

-- RANK_REQUIREMENTS TABLE
CREATE TABLE RANK_REQUIREMENTS (
    REQ_ID INT NOT NULL,
    RANK_ID INT NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY (REQ_ID),
    FOREIGN KEY (RANK_ID) REFERENCES RANKS(RANK_ID)
);

-- STU_RANKS TABLE 
CREATE TABLE STU_RANKS (
    STU_ID INT NOT NULL,
    RANK_ID INT NOT NULL,
    DATE_AWARDED DATE,
    PRIMARY KEY (STU_ID, RANK_ID),
    FOREIGN KEY (STU_ID) REFERENCES STUDENTS(STU_ID),
    FOREIGN KEY (RANK_ID) REFERENCES RANKS(RANK_ID)
);
